/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + database connectivity check
         * @description Runs `select 1` against PostgreSQL and reports service status.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an admin account
         * @description Open self-registration for the admin panel. Hashes the password, creates the admin_users row, and returns a signed JWT plus the public user.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate an admin and return a JWT */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated admin */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the published catalog
         * @description Returns published products matching the given attribute filters. The raw `color` term (possibly Jordanian dialect, e.g. "نبيتي") is normalized to a color family via color synonyms before matching. All filters are optional; with none, the full published catalog is returned.
         */
        get: operations["ProductsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published product by id */
        get: operations["ProductsController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload one or more images for a product
         * @description Accepts multipart/form-data with one or more image files (jpeg/png/webp). Each file is stored via the storage layer and its storage key is appended to the product's image_urls; the response returns the product with keys resolved to public URLs. Pass `replace=true` to overwrite instead.
         */
        post: operations["ProductImagesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products (admin)
         * @description Paginated product list visible to admins. Includes drafts by default. Pass `published=true` to narrow to published products only, or `published=false` to see only drafts.
         */
        get: operations["ProductsAdminController_list"];
        put?: never;
        /**
         * Create a product draft
         * @description Creates a new product in draft state (is_published = false). The product will not be visible to customers or the agent until published.
         */
        post: operations["ProductsAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a product
         * @description Hard-deletes the product row and returns the deleted product.
         */
        delete: operations["ProductsAdminController_remove"];
        options?: never;
        head?: never;
        /**
         * Update product fields
         * @description Partial (PATCH) update of a product. Only the supplied fields are changed. Drafts and published products are both reachable.
         */
        patch: operations["ProductsAdminController_update"];
        trace?: never;
    };
    "/admin/products/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the published flag
         * @description Explicitly set `is_published` to `true` or `false`. Prefer this over toggling when the desired state is known.
         */
        patch: operations["ProductsAdminController_setPublished"];
        trace?: never;
    };
    "/admin/products/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List product images
         * @description Returns all images for the product as `{ key, url, isPrimary }` objects. `url` is the public access URL resolved from the storage key. `isPrimary` is `true` only for the first entry (index 0).
         */
        get: operations["ProductImagesAdminController_listImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a product image
         * @description Removes the image from storage (R2) and strips its key from the product. Returns the updated product with image keys resolved to public URLs.
         */
        delete: operations["ProductImagesAdminController_removeImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{id}/images/{imageId}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Promote an image to primary
         * @description Reorders `imageUrls` so the given key appears at index 0 (primary). The remaining keys keep their relative order. Returns the updated product with image keys resolved to public URLs.
         */
        patch: operations["ProductImagesAdminController_setPrimaryImage"];
        trace?: never;
    };
    "/admin/ad-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ad-product links (admin)
         * @description Returns links ordered by position asc then created_at asc. Pass `ad_ref` to narrow to a single ad reference slug.
         */
        get: operations["AdProductLinksAdminController_list"];
        put?: never;
        /**
         * Create an ad-product link
         * @description Links a product to a Facebook ad reference slug. The linked product will be surfaced by the agent when a customer arrives from that ad (is_active = true).
         */
        post: operations["AdProductLinksAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ad-links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an ad-product link
         * @description Hard-deletes the link row and returns the deleted row.
         */
        delete: operations["AdProductLinksAdminController_remove"];
        options?: never;
        head?: never;
        /**
         * Update an ad-product link
         * @description Partial (PATCH) update of an ad-product link. Covers toggling `isActive` (deactivating a link removes it from the agent's ad-ref results without deleting it) and reordering via `position`.
         */
        patch: operations["AdProductLinksAdminController_update"];
        trace?: never;
    };
    "/admin/color-synonyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List color synonyms (admin)
         * @description Paginated list of color synonym mappings, newest first.
         */
        get: operations["ColorSynonymsAdminController_list"];
        put?: never;
        /**
         * Create a color synonym
         * @description Maps a dialect color term (e.g. "نبيتي") to a canonical color family (e.g. "red") so the agent can normalize customer language during product search.
         */
        post: operations["ColorSynonymsAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/color-synonyms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a color synonym
         * @description Hard-deletes the synonym row and returns the deleted row.
         */
        delete: operations["ColorSynonymsAdminController_remove"];
        options?: never;
        head?: never;
        /**
         * Update a color synonym
         * @description Partial (PATCH) update of a color synonym mapping.
         */
        patch: operations["ColorSynonymsAdminController_update"];
        trace?: never;
    };
    "/admin/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List knowledge entries (admin)
         * @description Paginated knowledge entry list visible to admins. Includes drafts by default. Pass `published=true` to narrow to published entries only, or `published=false` to see only drafts. Pass `product_id` to filter by product.
         */
        get: operations["KnowledgeController_list"];
        put?: never;
        /**
         * Create a knowledge entry draft
         * @description Creates a new knowledge entry in draft state (isPublished = false by default). The entry will not be visible to the agent until published. Pass productId to associate the entry with a specific product.
         */
        post: operations["KnowledgeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a knowledge entry
         * @description Hard-deletes the knowledge entry row and returns the deleted entry.
         */
        delete: operations["KnowledgeController_remove"];
        options?: never;
        head?: never;
        /**
         * Update knowledge entry fields
         * @description Partial (PATCH) update of a knowledge entry. Only the supplied fields are changed. Drafts and published entries are both reachable.
         */
        patch: operations["KnowledgeController_update"];
        trace?: never;
    };
    "/admin/knowledge/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set the published flag
         * @description Explicitly set `is_published` to `true` or `false`. Prefer this over toggling when the desired state is known.
         */
        patch: operations["KnowledgeController_setPublished"];
        trace?: never;
    };
    "/agent/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a customer message to the Masa sales agent
         * @description Accepts a ManyChat-compatible payload (contactId, text, optional image URL, ad ref, and profile name) and returns the agent reply plus any product cards extracted from search_products tool results. TEMPORARY — the real ManyChat webhook + Dynamic Block formatting is AIA-32 (Phase 4).
         */
        post: operations["AgentController_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponseDto: {
            accessToken: string;
            user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string | null;
                /** @enum {string} */
                role: "admin" | "editor";
            };
        };
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string | null;
            /** @enum {string} */
            role: "admin" | "editor";
        };
        ProductDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy: string | null;
            name: string;
            description: string | null;
            sku: string | null;
            priceJod: string;
            colorFamily: string | null;
            colorShade: string | null;
            sleeveType: string | null;
            fabric: string | null;
            embellishment: string | null;
            occasion: string | null;
            sizes: string[] | null;
            /** @enum {string} */
            stockStatus: "in_stock" | "low" | "out";
            imageUrls: string[] | null;
            tags: string[] | null;
            attributes: (((string | number | boolean) | null) | {
                [key: string]: unknown;
            } | unknown[]) | null;
            isPublished: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProductDto: {
            /** Format: uuid */
            createdBy?: string | null;
            name: string;
            description?: string | null;
            sku?: string | null;
            priceJod: string;
            colorFamily?: string | null;
            colorShade?: string | null;
            sleeveType?: string | null;
            fabric?: string | null;
            embellishment?: string | null;
            occasion?: string | null;
            sizes?: string[] | null;
            /** @enum {string} */
            stockStatus?: "in_stock" | "low" | "out";
            imageUrls?: string[] | null;
            tags?: string[] | null;
            attributes?: (((string | number | boolean) | null) | {
                [key: string]: unknown;
            } | unknown[]) | null;
            isPublished?: boolean;
        };
        UpdateProductDto: {
            /** Format: uuid */
            createdBy?: string | null;
            name?: string;
            description?: string | null;
            sku?: string | null;
            priceJod?: string;
            colorFamily?: string | null;
            colorShade?: string | null;
            sleeveType?: string | null;
            fabric?: string | null;
            embellishment?: string | null;
            occasion?: string | null;
            sizes?: string[] | null;
            /** @enum {string} */
            stockStatus?: "in_stock" | "low" | "out";
            imageUrls?: string[] | null;
            tags?: string[] | null;
            attributes?: (((string | number | boolean) | null) | {
                [key: string]: unknown;
            } | unknown[]) | null;
            isPublished?: boolean;
        };
        PaginatedProductsDto: {
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                createdBy: string | null;
                name: string;
                description: string | null;
                sku: string | null;
                priceJod: string;
                colorFamily: string | null;
                colorShade: string | null;
                sleeveType: string | null;
                fabric: string | null;
                embellishment: string | null;
                occasion: string | null;
                sizes: string[] | null;
                /** @enum {string} */
                stockStatus: "in_stock" | "low" | "out";
                imageUrls: string[] | null;
                tags: string[] | null;
                attributes: (((string | number | boolean) | null) | {
                    [key: string]: unknown;
                } | unknown[]) | null;
                isPublished: boolean;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            total: number;
            limit: number;
            offset: number;
        };
        CreateAdProductLinkDto: {
            adRef: string;
            /** Format: uuid */
            productId: string;
            position?: number;
            isActive?: boolean;
            campaign?: string | null;
        };
        AdProductLinkDto: {
            /** Format: uuid */
            id: string;
            adRef: string;
            /** Format: uuid */
            productId: string;
            position: number;
            isActive: boolean;
            campaign: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateAdProductLinkDto: {
            adRef?: string;
            /** Format: uuid */
            productId?: string;
            position?: number;
            isActive?: boolean;
            campaign?: string | null;
        };
        CreateColorSynonymDto: {
            term: string;
            canonicalFamily: string;
        };
        ColorSynonymDto: {
            /** Format: uuid */
            id: string;
            term: string;
            canonicalFamily: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateColorSynonymDto: {
            term?: string;
            canonicalFamily?: string;
        };
        CreateKnowledgeEntryDto: {
            /** Format: uuid */
            createdBy?: string | null;
            /** @enum {string} */
            category: "faq" | "policy" | "shipping" | "returns" | "sizing" | "payment" | "care" | "canned_response" | "product_info" | "general";
            title: string;
            content: string;
            tags?: string[] | null;
            priority?: number;
            isPublished?: boolean;
            /** Format: uuid */
            productId?: string | null;
            situation?: string | null;
        };
        KnowledgeEntryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy: string | null;
            /** @enum {string} */
            category: "faq" | "policy" | "shipping" | "returns" | "sizing" | "payment" | "care" | "canned_response" | "product_info" | "general";
            title: string;
            content: string;
            tags: string[] | null;
            priority: number;
            isPublished: boolean;
            /** Format: uuid */
            productId: string | null;
            situation: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateKnowledgeEntryDto: {
            /** Format: uuid */
            createdBy?: string | null;
            /** @enum {string} */
            category?: "faq" | "policy" | "shipping" | "returns" | "sizing" | "payment" | "care" | "canned_response" | "product_info" | "general";
            title?: string;
            content?: string;
            tags?: string[] | null;
            priority?: number;
            isPublished?: boolean;
            /** Format: uuid */
            productId?: string | null;
            situation?: string | null;
        };
        PaginatedKnowledgeDto: {
            items: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                createdBy: string | null;
                /** @enum {string} */
                category: "faq" | "policy" | "shipping" | "returns" | "sizing" | "payment" | "care" | "canned_response" | "product_info" | "general";
                title: string;
                content: string;
                tags: string[] | null;
                priority: number;
                isPublished: boolean;
                /** Format: uuid */
                productId: string | null;
                situation: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            total: number;
            limit: number;
            offset: number;
        };
        IncomingMessageDto: {
            contactId: string;
            text: string;
            /** Format: uri */
            lastImageUrl?: string;
            adRef?: string;
            name?: string;
        };
        AgentReplyDto: {
            reply: string;
            products?: {
                id: string;
                name: string;
                price: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up and the database is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * Format: date-time
                         * @example 2026-06-15T12:00:00.000Z
                         */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Account created; JWT issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Authenticated; JWT issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current admin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_search: {
        parameters: {
            query?: {
                /** @description Occasion filter. */
                occasion?: unknown;
                /** @description Fabric filter. */
                fabric?: unknown;
                /** @description Requested size. */
                size?: unknown;
                /** @description Canonical color family; takes precedence over `color` when provided. */
                colorFamily?: unknown;
                /** @description Customer color term; normalized via color synonyms (e.g. "نبيتي" → red). */
                color?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching published products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"][];
                };
            };
            /** @description Unknown query parameter or invalid filter value. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The published product. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description No published product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductImagesController_upload: {
        parameters: {
            query?: {
                /** @description When `true`, replaces image_urls instead of appending. */
                replace?: string;
            };
            header?: never;
            path: {
                /** @description Product UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files?: string[];
                };
            };
        };
        responses: {
            /** @description The updated product. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description The request carried no files. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A file exceeded the maximum allowed size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A file was not an allowed image type (jpeg/png/webp). */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_list: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                /** @description Filter by publish state. */
                published?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated product list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductsDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Product draft created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Product updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsAdminController_setPublished: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_published: boolean;
                };
            };
        };
        responses: {
            /** @description Publish flag updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductImagesAdminController_listImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of image descriptors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example abc123.jpg */
                        key?: string;
                        /** Format: uri */
                        url?: string;
                        isPrimary?: boolean;
                    }[];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductImagesAdminController_removeImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID. */
                id: string;
                /** @description Storage key of the image (e.g. `abc123.jpg`). */
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image deleted; updated product returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id, or the key is not present. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductImagesAdminController_setPrimaryImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product UUID. */
                id: string;
                /** @description Storage key of the image to promote. */
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Primary image updated; updated product returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that id, or the key is not present. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdProductLinksAdminController_list: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                /** @description Filter by ad reference slug. */
                ad_ref?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ad-product links. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdProductLinkDto"][];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdProductLinksAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdProductLinkDto"];
            };
        };
        responses: {
            /** @description Link created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdProductLinkDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Referenced product does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdProductLinksAdminController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdProductLinkDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No link exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdProductLinksAdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdProductLinkDto"];
            };
        };
        responses: {
            /** @description Link updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdProductLinkDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No link or product exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorSynonymsAdminController_list: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of color synonyms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorSynonymDto"][];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorSynonymsAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColorSynonymDto"];
            };
        };
        responses: {
            /** @description Synonym created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorSynonymDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorSynonymsAdminController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synonym deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorSynonymDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No synonym exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ColorSynonymsAdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColorSynonymDto"];
            };
        };
        responses: {
            /** @description Synonym updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorSynonymDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No synonym exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeController_list: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                /** @description Filter by publish state. */
                published?: unknown;
                /** @description Filter by product UUID. */
                product_id?: unknown;
                /** @description Filter by category. */
                category?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated knowledge entry list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedKnowledgeDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeEntryDto"];
            };
        };
        responses: {
            /** @description Knowledge entry draft created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntryDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No product exists with that productId (when productId is provided). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Knowledge entry deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntryDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No entry exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKnowledgeEntryDto"];
            };
        };
        responses: {
            /** @description Knowledge entry updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntryDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No entry exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    KnowledgeController_setPublished: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_published: boolean;
                };
            };
        };
        responses: {
            /** @description Publish flag updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntryDto"];
                };
            };
            /** @description Missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No entry exists with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentController_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomingMessageDto"];
            };
        };
        responses: {
            /** @description The agent reply plus any product cards to surface. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentReplyDto"];
                };
            };
        };
    };
}
